const arrowSvg="<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 70.5 65.3\" aria-hidden=\"true\" focusable=\"false\"><polygon fill=\"currentColor\" points=\"0 29.2 59.5 30.1 34.1 10.1 34.1 0 70.5 32.7 0 32.7 0 29.2\"/><polygon fill=\"currentColor\" points=\"0 36.1 59.5 35.3 34.1 55.2 34.1 65.3 70.5 32.7 0 32.7 0 36.1\"/></svg>";
function sectionName(value){return value.toLowerCase().replace(/\b[a-z]/g,c=>c.toUpperCase())}
let groups=[];const tabs=document.querySelector('#tabs'),content=document.querySelector('#content');
function el(tag,text,cls){let n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n}
function link(url,text,cls){let a=el('a',text,cls);a.href=url;a.target='_blank';a.rel='noopener noreferrer';return a}
function card(e){let c=el('article',null,'card'),v=e.url?link(e.url,null,'visual'):el('div',null,'visual');v.setAttribute('aria-label','View '+e.name+' portfolio');if(e.image){let im=el('img');im.src=e.image;im.alt='Selected work from '+e.name;im.loading='lazy';im.onerror=()=>{im.remove();fallback(v,e)};v.append(im)}else fallback(v,e);c.append(v);let i=el('div',null,'info'),row=el('div',null,'name-row'),h=el('h3');h.append(e.url?link(e.url,e.name):el('span',e.name));row.append(h);if(e.url){let a=link(e.url,null,'website-link');a.setAttribute('aria-label','View '+e.name+' website');a.innerHTML=arrowSvg;row.append(a)}i.append(row);if(e.notes.length)i.append(el('p',e.notes.join(' · '),'notes'));let ls=el('div',null,'links');e.links.filter(u=>u!==e.url).forEach(u=>ls.append(link(u,u.startsWith('mailto:')?'Email':'Additional link')));i.append(ls);c.append(i);return c}
function fallback(v,e){let f=el('div',null,'fallback');f.append(el('strong',e.name));f.append(el('span',e.imageStatus||'No portfolio image'));v.append(f)}
function show(i,focus=false){let g=groups[i];document.querySelector('#category').textContent=g.name;document.querySelector('#count').textContent=g.entries.length+' '+(g.entries.length===1?'entry':'entries');content.replaceChildren();[...tabs.children].forEach((b,j)=>{b.setAttribute('aria-selected',j===i);b.tabIndex=j===i?0:-1});content.setAttribute('aria-labelledby','tab-'+i);let last=null,grid;if(!g.entries.length)content.append(el('p','No entries in this tab yet.','empty'));for(let e of g.entries){if(!grid||e.section!==last){if(e.section)content.append(el('h3',sectionName(e.section),'subhead'));grid=el('div',null,'grid');content.append(grid);last=e.section}grid.append(card(e))}history.replaceState(null,'','#'+encodeURIComponent(g.name));if(focus)tabs.children[i].focus()}

let fingerprint='',busy=false;
function render(data){let selected;try{selected=decodeURIComponent(location.hash.slice(1))}catch{selected=''}groups=data;tabs.replaceChildren();data.forEach((g,i)=>{let b=el('button',g.name);b.id='tab-'+i;b.setAttribute('role','tab');b.setAttribute('aria-controls','content');b.onclick=()=>show(i);b.onkeydown=k=>{let next;if(k.key==='ArrowRight')next=(i+1)%groups.length;if(k.key==='ArrowLeft')next=(i-1+groups.length)%groups.length;if(k.key==='Home')next=0;if(k.key==='End')next=groups.length-1;if(next!==undefined){k.preventDefault();show(next,true)}};tabs.append(b)});let i=groups.findIndex(g=>g.name===selected);if(groups.length)show(i<0?0:i);else{content.replaceChildren(el('p','No tabs in the sheet yet.','empty'));document.querySelector('#category').textContent='Directory';document.querySelector('#count').textContent='0 entries'}}
async function refresh(){if(busy)return;busy=true;const status=document.querySelector('#sync-status');try{const r=await fetch('/api/directory',{cache:'no-store',signal:AbortSignal.timeout(25000)});if(!r.ok)throw Error();const data=await r.json();let next=JSON.stringify(data.groups);if(next!==fingerprint){render(data.groups);fingerprint=next}status.className=data.stale?'error':'';status.textContent=data.stale?'Showing the last successful update. The sheet is temporarily unavailable.':'Live sheet · Updated '+new Date(data.updatedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}catch{status.className='error';status.textContent=groups.length?'Unable to refresh. Your current entries are still available.':'Unable to read the live sheet. Check its viewing permissions, then reload.';if(!groups.length){document.querySelector('#category').textContent='Directory unavailable';content.replaceChildren(el('p','The directory will retry automatically.','empty'))}}finally{busy=false}}
if(window.__DIRECTORY__?.groups){render(window.__DIRECTORY__.groups);fingerprint=JSON.stringify(window.__DIRECTORY__.groups)}
refresh();setInterval(()=>{if(!document.hidden)refresh()},60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});
