function vimeoEmbed(value){try{const u=new URL(value);if(!['vimeo.com','www.vimeo.com','player.vimeo.com'].includes(u.hostname))return null;const parts=u.pathname.split('/').filter(Boolean);const index=parts.findIndex(p=>/^\d+$/.test(p));if(index<0)return null;const embed=new URL('https://player.vimeo.com/video/'+parts[index]);const hash=u.searchParams.get('h')||parts[index+1];if(hash&&/^[a-z0-9]+$/i.test(hash))embed.searchParams.set('h',hash);for(const [k,v] of Object.entries({autoplay:'1',muted:'1',loop:'1',autopause:'0',title:'0',byline:'0',portrait:'0'}))embed.searchParams.set(k,v);return embed.href}catch{return null}}
function isVideo(url){try{return /\.(mp4|webm)$/i.test(new URL(url,location.href).pathname)}catch{return false}}
const arrowSvg="<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 70.5 65.3\" aria-hidden=\"true\" focusable=\"false\"><polygon fill=\"currentColor\" points=\"0 29.2 59.5 30.1 34.1 10.1 34.1 0 70.5 32.7 0 32.7 0 29.2\"/><polygon fill=\"currentColor\" points=\"0 36.1 59.5 35.3 34.1 55.2 34.1 65.3 70.5 32.7 0 32.7 0 36.1\"/></svg>";
function sectionName(value){return value.toLowerCase().replace(/\b[a-z]/g,c=>c.toUpperCase())}
let groups=[];const tabs=document.querySelector('#tabs'),content=document.querySelector('#content');
function el(tag,text,cls){let n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n}
function link(url,text,cls){let a=el('a',text,cls);a.href=url;a.target='_blank';a.rel='noopener noreferrer';return a}
function card(e){let c=el('article',null,'card'),v=e.url?link(e.url,null,'visual'):el('div',null,'visual');v.setAttribute('aria-label','View '+e.name+' portfolio');if(e.image&&vimeoEmbed(e.image)){let frame=el('iframe');const src=new URL(vimeoEmbed(e.image));if(matchMedia('(prefers-reduced-motion: reduce)').matches)src.searchParams.set('autoplay','0');frame.src=src.href;frame.title='Portfolio video for '+e.name;frame.loading='lazy';frame.allow='autoplay; fullscreen; picture-in-picture';frame.allowFullscreen=true;v.append(frame)}else if(e.image){let video=isVideo(e.image),im=el(video?'video':'img');if(video){im.muted=true;im.loop=true;im.autoplay=!matchMedia('(prefers-reduced-motion: reduce)').matches;im.playsInline=true;im.preload='metadata';im.setAttribute('aria-label','Portfolio video for '+e.name)}else{im.alt='Selected work from '+e.name;im.loading='lazy'}im.src=e.image;im.onerror=()=>{im.remove();fallback(v,e)};v.append(im)}else fallback(v,e);c.append(v);let i=el('div',null,'info'),row=el('div',null,'name-row'),h=el('h3');h.append(e.url?link(e.url,e.name):el('span',e.name));row.append(h);if(e.url){let a=link(e.url,null,'website-link');a.setAttribute('aria-label','View '+e.name+' website');a.innerHTML=arrowSvg;row.append(a)}i.append(row);if(e.notes.length)i.append(el('p',e.notes.join(' · '),'notes'));let ls=el('div',null,'links');e.links.filter(u=>u!==e.url).forEach(u=>ls.append(link(u,u.startsWith('mailto:')?'Email':'Additional link')));i.append(ls);c.append(i);return c}
function fallback(v,e){let f=el('div',null,'fallback');f.append(el('strong',e.name));f.append(el('span',e.imageStatus||'No portfolio image'));v.append(f)}

const activeSubsections=new Map();
function show(i,focus=false){let g=groups[i];document.querySelector("#category").textContent=g.name;
const keys=[...new Set(g.entries.map(e=>e.section||''))];let selected=activeSubsections.get(g.name)??null;if(selected!==null&&!keys.includes(selected)){selected=null;activeSubsections.delete(g.name)}
const filters=document.querySelector('#subsection-filters');filters.replaceChildren();filters.hidden=!keys.some(Boolean);
if(!filters.hidden){for(const key of [null,...keys]){let b=el('button',key===null?'All':key?sectionName(key):'Other');b.type='button';b.setAttribute('aria-pressed',key===selected);b.onclick=()=>{activeSubsections.set(g.name,key);show(i);const index=[null,...keys].indexOf(key);filters.children[index]?.focus()};filters.append(b)}}
const entries=selected===null?g.entries:g.entries.filter(e=>(e.section||'')===selected);
content.replaceChildren();[...tabs.children].forEach((b,j)=>{b.setAttribute('aria-selected',j===i);b.tabIndex=j===i?0:-1});content.setAttribute('aria-labelledby','tab-'+i);let last=null,grid;if(!entries.length)content.append(el('p','No entries in this tab yet.','empty'));for(let e of entries){if(!grid||e.section!==last){if(e.section)content.append(el('h3',sectionName(e.section),'subhead'));grid=el('div',null,'grid');content.append(grid);last=e.section}grid.append(card(e))}history.replaceState(null,'','#'+encodeURIComponent(g.name));if(focus)tabs.children[i].focus()}

let fingerprint='',busy=false;
function render(data){let selected;try{selected=decodeURIComponent(location.hash.slice(1))}catch{selected=''}groups=data;tabs.replaceChildren();data.forEach((g,i)=>{let b=el('button',g.name);b.id='tab-'+i;b.setAttribute('role','tab');b.setAttribute('aria-controls','content');b.onclick=()=>show(i);b.onkeydown=k=>{let next;if(k.key==='ArrowRight')next=(i+1)%groups.length;if(k.key==='ArrowLeft')next=(i-1+groups.length)%groups.length;if(k.key==='Home')next=0;if(k.key==='End')next=groups.length-1;if(next!==undefined){k.preventDefault();show(next,true)}};tabs.append(b)});let i=groups.findIndex(g=>g.name===selected);if(groups.length)show(i<0?0:i);else{document.querySelector('#category').textContent='Directory';content.replaceChildren(el('p','No tabs in the sheet yet.','empty'));}}
async function refresh(){if(busy)return;busy=true;const status=document.querySelector('#sync-status');try{const r=await fetch('/api/directory',{cache:'no-store',signal:AbortSignal.timeout(25000)});if(!r.ok)throw Error();const data=await r.json();let next=JSON.stringify(data.groups);if(next!==fingerprint){render(data.groups);fingerprint=next}status.className=data.stale?'error':'';status.textContent=data.stale?'Showing the last successful update. The sheet is temporarily unavailable.':'Live sheet · Updated '+new Date(data.updatedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}catch{status.className='error';status.textContent=groups.length?'Unable to refresh. Your current entries are still available.':'Unable to read the live sheet. Check its viewing permissions, then reload.';if(!groups.length){content.replaceChildren(el('p','The directory will retry automatically.','empty'))}}finally{busy=false}}
if(window.__DIRECTORY__?.groups){render(window.__DIRECTORY__.groups);fingerprint=JSON.stringify(window.__DIRECTORY__.groups)}
refresh();setInterval(()=>{if(!document.hidden)refresh()},60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});

const directoryNavigation=document.querySelector('#directory-navigation');
const stickySentinel=document.querySelector('#sticky-sentinel');
let stickyFrame=false;
function updateStickyNavigation(){directoryNavigation.classList.toggle('is-stuck',stickySentinel.getBoundingClientRect().top<0);stickyFrame=false}
window.addEventListener('scroll',()=>{if(!stickyFrame){stickyFrame=true;requestAnimationFrame(updateStickyNavigation)}},{passive:true});
window.addEventListener('resize',updateStickyNavigation);
updateStickyNavigation();
